language: cpp

compiler:
  - clang
  - gcc

# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

addons:
  apt:
    packages:
      - build-essential
      - wget
      - libtool
      - cmake
#      - gcc-4.8
#      - clang-3.6
      - libcurl4-openssl-dev
      - libmicrohttpd-dev
      - uuid-dev
#      - uuid-runtime
      # leptonica
      - libpng-dev
      - libtiff4-dev

env:
  - CTEST_OUTPUT_ON_FAILURE=1

notifications:
    mail: "volkszaehler-dev@lists.volkszaehler.org"
    irc: "chat.freenode.net#volkszaehler.org"

cache:
  directories:
  - $HOME/json-c
  - $HOME/libsml
  - $HOME/libmbus

before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -qq
#  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

  - ls -R /usr/include/uuid
  - ls -R
  - bash install-libjson.sh
  - bash install-libsml.sh

# install json-c
  - git clone -b json-c-0.12 https://github.com/json-c/json-c
  - cd json-c
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
#  - sudo apt-get install -y  openssl uuid-dev uuid-runtime
# -- get libsml --
  - git clone https://github.com/volkszaehler/libsml.git # or github.com/TheCount/libsml.git # or https://github.com/dailab/libsml.git
  - cd libsml
  - # git checkout develop # only dev branch seems to work
  - make
# -- install libsml --
  - sudo cp sml/lib/libsml.* /usr/lib/.
  - sudo cp -R sml/include/* /usr/include/.
  - sudo cp sml.pc /usr/lib/pkgconfig/.
  - cd ..

# -- install leptonica
#  - sudo apt-get install libpng-dev libtiff-dev
  - wget http://www.leptonica.org/source/leptonica-1.71.tar.gz
  - tar -zxvf leptonica-1.71.tar.gz
  - cd leptonica-1.71
  - ./configure --disable-programs
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..

# -- install libmbus
  - git clone https://github.com/rscada/libmbus
  - cd libmbus
  - ./build.sh
  - sudo make install
  - cd ..

script:
  - cmake . -DENABLE_OCR=ON -DSML_HOME=/usr/local/src/libsml/sml && make && make test
